### ISSUE TITLE
Island Size changes without a reason

### ISSUE THREAD

**Issue by meytro** [tastybento/askyblock#225]
There is a problem with islands getting larger or smaller without a good reason or using the admin commands.

I'm using version 3.0.0.8 and will add more information when I come back home. Maybe you already know where the issue could be.

**Comment by tastybento** [comment]
There was an issue with an earlier version where island protection sizes were created at the maximum no matter what. That's fixed now.

**Comment by meytro** [comment]
This isn't fixed, with version 3.0.0.8 I get this message in the console. 

[ASkyBlock] Island protection range must be 185 or less, (island range -16). Setting to: 185

while:
distance: 201
protectionRange: 200
overridelimit: false

**Comment by tastybento** [comment]
The message is correct. overridelimit:**false** means that you have to have 16 blocks or more between distance and protectionRange. If you want them that close, then you need to set it to **true**. So, currently, your island protection range is 185. 
I don't understand what you mean about chunks outside the region being deleted - outside of which region?

**Comment by meytro** [comment]
Well in the config it says:
"If you want to have protection range = distance set the following to true."

Looks like that this changed in one of the last versions...
